/* Progressive enhancement. Core navigation/content/form do not require JavaScript. */
(()=>{
'use strict';
const menuButton=document.querySelector('.menu-toggle');
const menu=document.querySelector('#main-nav');
function closeMenu(){menu?.classList.remove('open');menuButton?.setAttribute('aria-expanded','false');menuButton?.setAttribute('aria-label','Abrir menú');}
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');menu.classList.toggle('open',open)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const wasOpen=menuButton?.getAttribute('aria-expanded')==='true';closeMenu();document.querySelectorAll('.nav-dropdown[open]').forEach(x=>x.removeAttribute('open'));if(wasOpen)menuButton.focus()}});
document.addEventListener('click',e=>{if(!e.target.closest('.site-header')){closeMenu();document.querySelectorAll('.nav-dropdown[open]').forEach(x=>x.removeAttribute('open'))}});
window.matchMedia('(min-width:721px)').addEventListener('change',e=>{if(e.matches)closeMenu()});
menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
const cards=[...document.querySelectorAll('.service-card[data-category]')];
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{const on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-pressed',String(on))});let count=0;cards.forEach(c=>{c.hidden=b.dataset.filter!=='all'&&c.dataset.category!==b.dataset.filter;if(!c.hidden)count++});const live=document.querySelector('#filter-status');if(live)live.textContent=`${count} servicios visibles`;}));
const slides=[{kicker:'HDPE Y SERVICIOS AMBIENTALES',title:'Conectamos proyectos.<br><em>Cuidamos el entorno.</em>',desc:'Termofusión, electrofusión y soluciones ambientales. Dos especialidades, un mismo compromiso con tu proyecto.',img:'img/ambiental.png'},{kicker:'TERMOFUSIÓN Y ELECTROFUSIÓN',title:'Uniones que conectan.<br><em>Proyectos que avanzan.</em>',desc:'Soluciones en tuberías HDPE: uniones, instalación y mantenimiento, con un alcance definido para cada requerimiento.',img:'img/hdpe.png'}];
document.querySelectorAll('[data-slide]').forEach(b=>b.addEventListener('click',()=>{const s=slides[Number(b.dataset.slide)];if(!s)return;document.querySelector('[data-hero-title]').innerHTML=s.title;document.querySelector('[data-hero-kicker]').textContent=s.kicker;document.querySelector('[data-hero-desc]').textContent=s.desc;document.querySelector('.hero .hero-photo').src=s.img;document.querySelectorAll('[data-slide]').forEach(x=>{const on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-pressed',String(on))})}));
const form=document.querySelector('.quote-form');
if(form){const select=form.querySelector('[name=servicio]');const fieldset=form.querySelector('#hdpe-fields');const status=form.querySelector('#form-status');const hdpe=['termofusion','electrofusion','instalacion-hdpe','ambas-lineas'];function syncService(){const show=hdpe.includes(select.value);fieldset.hidden=!show;fieldset.disabled=!show;}
const params=new URLSearchParams(location.search);const wanted=params.get('servicio');if(wanted&&[...select.options].some(o=>!o.disabled&&o.value===wanted))select.value=wanted;
const sector=params.get('sector');if(sector&&['Agua y saneamiento','Agricultura y riego','Energía','Minería e industria','Infraestructura','Organizaciones'].includes(sector))form.querySelector('[name=mensaje]').value=`Sector del proyecto: ${sector}.\n`;
select.addEventListener('change',syncService);syncService();
form.addEventListener('submit',e=>{if(['file:'].includes(location.protocol)||['localhost','127.0.0.1',''].includes(location.hostname)){e.preventDefault();status.textContent='Estás en una vista previa: no se ha enviado la solicitud. Usa “Preparar en WhatsApp” o abre el sitio publicado para enviar el formulario.';status.scrollIntoView({block:'nearest',behavior:'smooth'});}});
form.querySelector('#quote-whatsapp')?.addEventListener('click',()=>{if(!form.reportValidity())return;const fd=new FormData(form);const fields=[['Nombre','nombre'],['Empresa o entidad','empresa'],['Correo','email'],['Teléfono','telefono'],['Ubicación','ubicacion'],['Diámetro / SDR','diametro'],['Cantidad / longitud','cantidad'],['Requerimiento','mensaje']];let lines=['Hola, deseo solicitar una cotización a CARMA.',`Servicio: ${select.selectedOptions[0].textContent.trim()}`];fields.forEach(([label,key])=>{const value=String(fd.get(key)||'').trim();if(value)lines.push(`${label}: ${value}`)});const url='https://wa.me/51967051416?text='+encodeURIComponent(lines.join('\n'));window.open(url,'_blank','noopener,noreferrer');status.textContent='Se preparó el mensaje para WhatsApp. Revisa y envíalo desde esa aplicación; todavía no se ha enviado desde esta web.';});}

})();
